### ISSUE TITLE
SMOG-1 frekvencia

### ISSUE THREAD

**Issue by hodlemil** [apandy/zsebi#14]
A rádiózás résznél a SMOG-1 frekvenciáját be kellene írni, eddig képként volt, de nem volt jó a frekvencia. Jó frekvencia: 437,345 MHz

**Comment by faddiv** [comment]
Jelenleg ott semmi tartalom nincs (Csak bbb-k).

**Comment by hodlemil** [comment]
A csatolt képen látható helyre kell a frekvenciát beírni, ahogy a képre "hackeltem".
![frequency_band](https://user-images.githubusercontent.com/36796054/37295976-e7eadd30-2619-11e8-9921-b729a5e71d30.png)
