### ISSUE TITLE
Publikációk oldal

### ISSUE THREAD

**Issue by hodlemil** [apandy/zsebi#22]
A menüben a közösség gomb mellé egy publikációk gomb kerüljön, ami a publikációk oldalra mutat. Tartalma ez lenne: http://gnd.bme.hu/smog1/publikaciok.php
A tartalmat bemásolom, csak a váz legyen meg.

**Comment by faddiv** [comment]
Megvan. A Views/Publications/Index.cshtml-ben szerkeszd.
