### ISSUE TITLE
Adatbázis news tábla

### ISSUE THREAD

**Issue by hodlemil** [apandy/zsebi#3]
Szükség van még az adatbázis news táblájára? Ahogy nézem az articles táblában van belőle minden információ.

**Comment by faddiv** [comment]
Megnézem, és ha nincs használva eltávolítom.

**Comment by faddiv** [comment]
Ahogy nézem, az lenne a legjobb, ha csinálok egy scriptet, amivel a entity framework által generált modellel egységesíti, így a későbbiekben lehet azzal frissítő scripteket generáltatni.
Amit jelenleg generál az alapján két tábla van csak használatban: articles és team. Lehet-e a többit törölni?

**Comment by hodlemil** [comment]
Ha a weboldal nem használja lehet.
