### ISSUE TITLE
Adatbázis és honlap ékezetes betűk

### ISSUE THREAD

**Issue by hodlemil** [apandy/zsebi#4]
Van értelme az adatbázisban és az oldaon entitás használatának (&eacute; )?
Az adatbázis UTF8-ra van állítva, a html oldal karakter készletét is lehet UTF8-ra állítani.
A dotnet nem tudja kezelni az UTF8-at?

**Comment by faddiv** [comment]
Tudja kezelni az UTF8-at. Valahol nem jelenik meg rendesen az ékezetes karakter?

**Comment by hodlemil** [comment]
például az Articles táblázat HtmlBody oszlopában az ékezetes betűk entitásra vannak cserélve. A kérdés az, hogy ez szükséges vagy nyugodtan lehet ott is ékezetes betűket használni. Ahogy nézem nem mindenhol, tehát nem következetes.

**Comment by faddiv** [comment]
Ha adatbázisban van úgy, az lényegtelen. Ékezetekkel is, és kódokkal is megfelel. Csak pár speciális karakter igényli a kódokat.
