### ISSUE TITLE
Admin rész

### ISSUE THREAD

**Issue by hodlemil** [apandy/zsebi#5]
Az adminisztáció rész beüzemeléséhez mi kell és ez a rész miből áll?

**Comment by faddiv** [comment]
Admin oldal a /Admin linken érhető el. Jelenleg ahogy nézem még nincs bejelentkezéshez kötve.Ez is egy későbbi task-ként fel lehet venni.

**Comment by hodlemil** [comment]
Akkor valami gond van vele, mivel a bmegnd-n lévő admin oldal hibát dob, nem töltődik be.

**Comment by faddiv** [comment]
Megoldva.
